services:
    devicehub-mongo:
        image: mongo:7.0
        hostname: devicehub-mongo
        container_name: devicehub-mongo
        ports:
            - 27017:27017
        entrypoint: ["mongod", "--replSet", "devicehub-rs", "--bind_ip_all"]
        healthcheck:
            test: echo "rs.status()" | mongosh --port 27017 --quiet
            interval: 5s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
        networks:
            - devicehub
    devicehub-mongosetup:
        image: mongo:7.0
        container_name: devicehub-mongosetup
        depends_on:
            devicehub-mongo:
                condition: service_healthy
        volumes:
            - ./scripts/mongo_setup.sh:/scripts/mongo_setup.sh
        restart: "no"
        entrypoint: ["bash", "/scripts/mongo_setup.sh"]
        networks:
            devicehub:

networks:
    devicehub:
        driver: bridge
