name: Run API Tests

on:
    push:
        paths:
            - 'lib/**'
            - 'Dockerfile'
            - 'test/api/**'
            - 'docker-compose-test.yaml'
    pull_request:
        paths:
            - 'lib/**'
            - 'Dockerfile'
            - 'test/api/**'
            - 'docker-compose-test.yaml'
jobs:
    run-api-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Compose
              uses: docker/setup-buildx-action@v3

            - name: Run API tests
              run: docker compose -f docker-compose-test.yaml up --exit-code-from devicehub-pytest --abort-on-container-exit devicehub-pytest --remove-orphans

            - name: Check generate device logs
              run: docker compose -f docker-compose-test.yaml logs devicehub-generate-fake-device
